spring:
  profiles:
    active: dev
  datasource:
    # jdbc数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # druid相关配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver

  # redis配置
  redis:
    jedis:
      pool:
        # 最大连接数
        max-active: 200
        # 最小空闲连接
        min-idle: 0
        # 最大阻塞等待时间
        max-wait: -1
        # 最大空闲连接
        max-idle: 10
    # 连接超时时间（毫秒）
    timeout: 10000

# mybatis配置
mybatis:
  type-aliases-package: top.doraemonqwq.dora.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
