spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dora?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456

  redis:
    database: 0
    # redis ip地址
    host: 127.0.0.1
    port: 6379
    password: 123456